### ISSUE TITLE
Documentation on github actions workflows

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#49]
We've recently revamped the github action workflows to use 'composite workflows', and tried to consolidate as much as possible. The [README.md](./github/workflows/README.md), could be updated for clarity https://github.com/uwhackweek/jupyterbook-template/pull/45#discussion_r780438859 

Also per discussion, I think that README.md could also have a 'Best Practices' section for *modifying* the workflows. For example, as discussed [here ](https://github.com/uwhackweek/jupyterbook-template/pull/44#pullrequestreview-846027701), it's sometimes desirable for the default [test.yaml](./github/workflows/test.yaml) workflow to have access to credentials. This was the case for SnowEx hackweek so that tutorial notebooks had access to NASA Logins to access remote data. In this case the default 'test.yaml' workflow can be modified to require a label being set by an administrator before it is run: 

```yaml
on:
  pull_request_target:
    types: [labeled, synchronize]
jobs:
  build-and-test:
    # This workflow accesses secrets and checks out a PR, so only run if labelled
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    if: contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
```
https://github.com/snowex-hackweek/website/blob/ffd063b9cfba8f4c92642466544d147e776db9ae/.github/workflows/test.yaml
